### PR TITLE
Pilot lacks full export information (#26)

### PR DESCRIPTION
**Pull request by lacostej**

### CODE REVIEW

**Comment by KrauseFx** [comment]
Do we really need this information when exporting? As far as I know the main use case for exporting the testers is to import them again on a different account.

**Comment by eytanbiala** [comment]
My original use case for including such information is to be able to use it as criteria when adding these users to a mailing list and emailing only certain ones, for example all users with last install before/after [version].

**Comment by lacostej** [comment]
My current use case: retrieve the export with full data, pass it on to those who follow up the users for marketing or technical reasons. Knowing which version the user has installed decides which message to send:
* upgrade to the latest
* give feedback
* remimder: try our app
Etc

A few more ideas:
* I haven't looked at it yet, I wonder if there's more information. Maybe date the user was added to the list, etc
* if that date exists I would prefer the list to be sorted by this date
* if uncomfortable with full output by default we can have a format option like the one I added to codes
* date format is US format it seems. Maybe could be locale dependebt, forced international (2015-07-12) or with letters to reduce interpretation risks

**Comment by KrauseFx** [comment]
@lacostej Fair enough. I think we have this code with the date formatting, etc. somewhere else already, right? Could you merge the 2 so we only have the code once?

**Comment by lacostej** [comment]
@KrauseFx  I refactored the code. Is it what you meant ?

I checked the data in the tester class and there' not much more I would want.

Example:
`````
{"emailAddress":{"value":"HIDEN","isEditable":false,"isRequired":false,"errorKeys":null,"maxLength":2147483647,"minLength":0},"firstName":{"value":"HIS FIRST NAME","isEditable":false,"isRequired":false,"errorKeys":null,"maxLength":2147483647,"minLength":0},"lastName":{"value":"HIS LAST NAME","isEditable":false,"isRequired":false,"errorKeys":null,"maxLength":2147483647,"minLength":0},"testerId":"XXXXXXXX-d0c2-48ee-ba49-17befa189c61","devices":[{"model":"iPad Air Wi-Fi","os":"iOS","osVersion":"8.4","name":null},{"model":"iPad 2 Wi-Fi","os":"iOS","osVersion":"8.4","name":null}],"latestInstalledAppAdamId":1005050125,"latestInstalledVersion":"1.0.1","latestInstalledShortVersion":"1.0.1","latestInstalledDate":1439291010360,"latestInstalledName":"DragonBox Numbers","latestInstallByPlatform":null,"hasAddedOrInvitedApp":null,"warnOnDelete":true,"itcUsername":null,"groups":[]}
``````
it's not possible to sort by recruitment date it seems

So the last remaining ideas are:
* user specified output like https://github.com/fastlane/codes/blob/master/lib/codes/itunes_connect.rb#L62-L75 y/n ?
* locale dependent date formater

**Comment by KrauseFx** [comment]
@lacostej to get rid of the HoundCI warnings, merge master back into your branch to get the latest hound config.

**Comment by lacostej** [comment]
yup sorry. Just saw that

**Comment by lacostej** [comment]
@KrauseFx hound and rubocop aren't exactly configured in the same way it seems.

**Comment by KrauseFx** [comment]
Looks much better, thanks @lacostej. But why did you decide to go for a helper class? Couldn't we just add methods to the existing `Tester` class to make things cleaner? This way we could just use `tester.pretty_date`.

**Comment by lacostej** [comment]
@KrauseFx tester is in core I think. I didn't want to force to update the dependency (it makes it harder to test the full PR). I could have dynamically modified the tester class instead until we update the dep. I am very cautious about that (because it's I think easier to think that a class is declared in one place).

But seing your comment, I will refactor it and make it so that we can migrate this to the core soon enough.

**Comment by KrauseFx** [comment]
Yes, that's what I meant: not putting the code into core, but extending core, like you did :+1:

**Comment by KrauseFx** [comment]
Perfect :rocket:

**Pull request merged**
